runtime: nodejs22
env: standard
instance_class: F1
handlers:
  - url: /.*
    script: auto
    secure: always
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: bestwestern-426207@appspot.gserviceaccount.com
